[tool.poetry]
name = "repl_python3_MeanNextExtension"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
discord = "^1.0.1"
Flask = "^2.0.0"
PyNaCl = "^1.4.0"
ffmpeg = "^1.4"
"discord.py" = "^1.7.3"
youtube_dl = "^2021.6.6"
DiscordUtils = "^1.3.4"
python-dotenv = "^0.19.2"
dotenv = "^0.0.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
