[build-system]
    requires = ["setuptools", "wheel"]
    build-backend = "setuptools.build_meta"

[tool.black]
    line-length = 99
    required-version = '22.1.0'
    target-version = ['py38']
    include = '\.py$'
    force-exclude = '''
    /(
        redbot\/vendored
    )/
    '''
