<!DOCTYPE html>
<html>
  <head>
	<meta name="robots" content="all">
    <title>DISCORD.de</title>
  </head>
  <body style="background:linear-gradient(#1234,#4567)">
	<div style="text-align:center"><h1 style="color:red"><i><font style="background-color:green" face="Comic Sans MS">DISCORD BOTS</h1>
    <a href='servers.php'><input style="border-top-left-radius:40px;border-top-right-radius:5px;border-bottom-left-radius:5px;border-bottom-right-radius:40px;color:white; background-color:red" type='button' value='SERVERS'></a>
	<a href='share-server.php'><input style="border-top-left-radius:40px;border-top-right-radius:5px;border-bottom-left-radius:5px;border-bottom-right-radius:40px;color:white; background-color:red" type='button' value='SHARE-SERVER'></a>
	<a href='share-bot.php'><input style="border-top-left-radius:40px;border-top-right-radius:5px;border-bottom-left-radius:5px;border-bottom-right-radius:40px;color:white; background-color:red" type='button' value='SHARE-BOT'></a><br><br>
  </body><a href="https://discordapp.com/oauth2/authorize?client_id=622430471980187649&scope=bot&permissions=477457878"><input style="color:white; background-color:blue" type="button" value="Retr0n "><br>= | Guild Security<br><br><a href="https://discordapp.com/oauth2/authorize?client_id=672376368763371520&scope=bot&permissions=2146958847"><input style="color:white; background-color:blue" type="button" value="Whistle Sync & Bump"><br>WHhelp | Bumping<br><br><a href="https://discordapp.com/oauth2/authorize?client_id=642328970334961695&permissions=8&redirect_uri=https%3A%2F%2Fdiscord.gg%2F3mEb7aT&response_type=code&scope=bot"><input style="color:white; background-color:blue" type="button" value="Scale"><br>s! <br><br><a href="https://discordapp.com/oauth2/authorize?client_id=242730576195354624&scope=bot&permissions=1576533239"><input style="color:white; background-color:blue" type="button" value="Auttaja"><br>@Auttaja help<br><br><a href="https://rythmbot.co/releases"><input style="color:white; background-color:blue" type="button" value="Rythm"><br>These are all Rythm bots like <br>Rythm#3722 <br> Rythm 2#2000 <br>Rythm Canary#8406<br><br><a href="https://mee6.xyz/"><input style="color:white; background-color:blue" type="button" value="MEE6"><br>!   |   Leveling and Moderation<br><br><a href="https://discordapp.com/oauth2/authorize?client_id=234395307759108106&permissions=37080136&redirect_uri=http://groovy.bot/callback&response_type=code&scope=bot%20identify%20guilds%20email"><input style="color:white; background-color:blue" type="button" value="groovy prefix -"><br>music<br><br><a href="https://discordapp.com/oauth2/authorize?permissions=301001759&scope=bot&client_id=239631525350604801"><input style="color:white; background-color:blue" type="button" value="pancake (prefix p!)"><br>memes and moderation<br><br><a href="https://discordapp.com/oauth2/authorize?client_id=543071379294126080&scope=bot&permissions=402713671&redirect_uri=https://shortrsg.cf%2Fdiscord"><input style="color:white; background-color:blue" type="button" value="Artificial Intelligence"><br>This Bot will do what you teach it<br><br>