<!DOCTYPE html>
<html>
  <head>
	<meta name="robots" content="all">
    <title>DISCORD.de</title>
  </head>
  <body style="background:linear-gradient(#1234,#4567)">
	<div style="text-align:center"><h1 style="color:red"><i><font style="background-color:green" face="Comic Sans MS">DISCORD SERVERS</h1>
    <a href='bots.php'><input style="border-top-left-radius:40px;border-top-right-radius:5px;border-bottom-left-radius:5px;border-bottom-right-radius:40px;color:white; background-color:red" type='button' value='BOTS'></a>
	<a href='share-server.php'><input style="border-top-left-radius:40px;border-top-right-radius:5px;border-bottom-left-radius:5px;border-bottom-right-radius:40px;color:white; background-color:red" type='button' value='SHARE-SERVER'></a>
	<a href='share-bot.php'><input style="border-top-left-radius:40px;border-top-right-radius:5px;border-bottom-left-radius:5px;border-bottom-right-radius:40px;color:white; background-color:red" type='button' value='SHARE-BOT'><br><br></a><a href="https://discord.gg/tKyTM3"><input type="button" style="color:white; background-color:blue" value="	Bots;Robots"><br>Here you can share your discord-bots you made<br><br><a href="https://discord.gg/ju8pP4f"><input style="color:white; background-color:blue" type="button" value="LEARNING BOT server"><br>This is the server of the learning bot LEARNING BOT THROUG TALKS PRE ><br><br><a href="https://discord.gg/Bg2MKvP"><input style="color:white; background-color:blue" type="button" value="slope"><br>Anyone who knows the game slope knows this server<br><br><a href="https://discord.gg/skyblivion"><input style="color:white; background-color:blue" type="button" value="Skyblivion Comunity Server"><br>What is Skyblivion? A: Skyblivion is a fan made recreation of the 4th Elder Scrolls game, Oblivion, in the Skyrim engine.  Our goal is to bring give the Elder Scrolls community a free remaster of Oblivion that includes all weapons, armors, quests, locations and NPC’s. All of this free of charge.<br><br><a href="https://discord.gg/VxMGPwH"><input style="color:white; background-color:blue" type="button" value="Bot Hosting"><br>We will host your discord-bot for free<br><br><a href="https://discord.gg/xxVWv4y"><input style="color:white; background-color:blue" type="button" value="a6d - Community Discord"><br>a place for fan's of a6d to join and interact or whatever, its just his official server ok<br><br><a href="https://invite.gg/rf.hq"><input style="color:white; background-color:blue" type="button" value="RF Headquarter"><br>Website<br><br><a href="https://discord.gg/rythm"><input style="color:white; background-color:blue" type="button" value="Rythm"><br>The official server of all Rythm bots<br><br><a href="https://discord.gg/CxGWTBX"><input style="color:white; background-color:blue" type="button" value="Streamers Treehouse"><br>Hello! We are looking for new members 🎮<br><br>