name: Docker Image Build Test CI

on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:

  testbuild:

    runs-on: ubuntu-latest

    steps:
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: false
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/valorant-bot:latest