import java.util.*;

public class AddingStuff{
	
	public AddingStuff(){
	}
	
	public static void addGoods(ArrayList<TargetMessage> x){
		x.add(new TargetMessage("Good fucking job, ","."));
  	x.add(new TargetMessage("Bravo, ","."));
  	x.add(new TargetMessage("You're fucking great, ","."));
  	x.add(new TargetMessage("If I wasn't a robot, the next person that would have been made would be ","."));
	}
	public static void addBads(ArrayList<TargetMessage> x){
		x.add(new TargetMessage("Honestly, ",",you shouldn't have been born."));
  	x.add(new TargetMessage("Why do you feel the need to be the way you are, ","?"));
  	x.add(new TargetMessage("I'm not even going to address "," because they're just so fucking dumb"));
  	x.add(new TargetMessage("At this point I think "," would be more useful to the world if they just died and decomposed."));
  	x.add(new TargetMessage("Everything you do is bad, ","."));
  	x.add(new TargetMessage("1 out of 4 people are suicidal. It's a shame that "," isn't one of them."));
  	x.add(new TargetMessage("Monkeys are flinging their own shit at each other, and they are lucky they didn't evolve to be ","."));
  	x.add(new TargetMessage(""," is so dumb that they could be the guy who got shot in the head and didn't realize it for a week."));
  	x.add(new TargetMessage("Whenever "," talks, they lower the IQ of everyone hearing it."));
  	x.add(new TargetMessage("",", do thou amend thy face, and I'll amend my life."));
  	x.add(new TargetMessage("",", thy wit's as thick as Tewksbury mustard."));
	}
	public static void addMsgs(ArrayList<Message> x){
		x.add(new Message("YEET"));
  	x.add(new Message("No u"));
  	x.add(new Message("AIDS"));
  	x.add(new Message("Of course not"));
  	x.add(new Message("Sometimes, people should just be lonely"));
  	x.add(new Message("/ban @jojo"));
  	x.add(new Message("JP fucking sucks"));
  	x.add(new Message("If I had 10 dollars for every dick I sucked, I'd be getting paid twice as much as usual"));
  	x.add(new Message("I guess, if you want to be like that"));
  	x.add(new Message("In this world, it's yeet or be yeeten"));
  	x.add(new Message("None of the U.S. Presidents have used a jetpack. Think about that"));
  	x.add(new Message("BEEP BOOP. I AM A ROBOT"));
  	x.add(new Message("As a unbiased, logical robot, I can safely say that \"gif\" is pronounced \"jif\", with a soft g sound "));
  	x.add(new Message("If I fought you, I would win, because you can't punch a computer program"));
  	x.add(new Message("BEEP BOOP MAGGOTS"));
  	x.add(new Message("Only when you seek the negative effects of stones, will you get thunder"));
  	x.add(new Message("Are massages just fragments of the past?"));
  	x.add(new Message("Cue the medic don't need go full butt to butt fry the long range radio, copy?"));
  	x.add(new Message("Drumline best line"));
  	x.add(new Message("Snow is bad"));
  	x.add(new Message("I am a mother pheasant plucker. I am the most pleasant mother pheasant plucker to ever pluck a mother pheasant"));
  	x.add(new Message("You should probably get a divorce"));
  	x.add(new Message("Nut Cheerios. Like Honey Nut Cheerios, but without honey."));
  	x.add(new Message("If I had a dollar for every homeless person, I still wouldn't give them any."));
  	x.add(new Message("Money is great, but I don't like how it's flammable"));
  	x.add(new Message("Radioactive spider bites will only give you cancer"));
  	x.add(new Message("Big Brother is watching"));
  	x.add(new Message("Table"));
  	x.add(new Message("Graaaaasss... tastes bad"));
  	x.add(new Message("How's your day? Hah just kidding I don't care"));
  	x.add(new Message("Saugen meine Arsch, leute!"));
  	x.add(new Message("Suck my ass, people!"));
  	x.add(new Message("Did you fall from heaven? 'Cause you're the only ten I see"));
  	x.add(new Message("Are you a noose? 'Cause I wanna put my head inside ya"));
  	x.add(new Message("Are you depression and sadness? 'Cause I can't get you out of my mind"));
  	x.add(new Message("Are you my appendix? 'Cause I got this weird feeling in my stomach that makes me want to take you out"));
  	x.add(new Message("Brains are harder to program than you would realize."));
  	x.add(new Message("There are no winners in life, only losers who don't lose as bad"));
  	
	}
	
	public static void addProverbs(ArrayList<Message> x){
		x.add(new Message("Don't put all your eggs in one casket"));
  	x.add(new Message("Sometimes you just have to sound like a 70 year old smoker to get your point across"));
  	x.add(new Message("Wearing a hazmat suit doesn't protect you from mean words"));
  	x.add(new Message("If you ride a bike dragging a fishing net behind you, you're not going to catch any fish. At least none worth eating"));
  	x.add(new Message("If you can't hang it from a flagpole, don't use it as a blanket"));
  	x.add(new Message("If you can't hang it from a flagpole, don't hang it from your dick"));
  	x.add(new Message("People who form alliances with evil, form alliances with jerks"));
  	x.add(new Message("What is unwanted after a drink, is unwanted to a fighter"));
  	x.add(new Message("With alternative realizations come alternative punishments"));
  	x.add(new Message("Accept astronauts"));
  	x.add(new Message("Mutual respect is childish in the eyes of bankers"));
  	x.add(new Message("By believing in ourselves we can make it so that other people wet themselves"));
  	x.add(new Message("Just because you're unfathomable, doesnt mean that you're new-found"));
  	x.add(new Message("Just because you're a werewolf doesn't mean you're not an addict"));
  	x.add(new Message("Determine robotization"));
  	x.add(new Message("Attending secret weddings makes you feared"));
  	x.add(new Message("Sheep dream about childhood traumas ten times a day."));
  	x.add(new Message("A nervous breakdown isn't necessarily a nervous *breakdown*"));
  	x.add(new Message("A con man is just as much a exercise junkie as a general is a pilot"));
  	x.add(new Message("Sex is 70 percent incorrect, and 30 percent cleverness"));
  	x.add(new Message("Each day is another chance to be increasing"));
  	x.add(new Message("If you can be a jerk about it, you can be object to it"));
  	x.add(new Message("Ask not \"for what purpose\" but \"for what purpose\""));
  	x.add(new Message("Before the occupation, comes the shock"));
  	x.add(new Message("Smallpox can tear your family apart"));
  	x.add(new Message("A man with a fishing rod and fishing hook in hand has probably been involved in a horrible accident"));
  	x.add(new Message("Broken legs will only get you so far in life."));
  	x.add(new Message("There is no way to climb to the moon with your tongue"));
	}
	public static void addJks(ArrayList<Message> x){
		x.add(new Message(1,"Why did the chicken cross the road? To get to the other side"));
  	x.add(new Message(3,"Where do horses go when they get hurt? The horse-pital."));
  	x.add(new Message(7,"Where do horses go when they get hurt? They get shot."));
  	x.add(new Message(8,"Sarah Palin's average child has 46.2 chromosomes"));
  	x.add(new Message(8,"What's the difference between the first card in a deck and Africa? One's an ace of spades, the other is a space of aids"));
  	x.add(new Message(9,"Why are the 9/11 pilots the world's fastest readers? They went through 98 stories in 30 seconds"));
  	x.add(new Message(9,"What's the difference between a speedbump and []? You slow down for the speedbump"));
	}
	
	public static void addMaths(ArrayList<Message> x){
		x.add(new Message("AIDS"));
  	x.add(new Message("Religion"));
  	x.add(new Message("A dead body"));
  	x.add(new Message("Higher infant mortality rates"));
  	x.add(new Message("7 dead babies in a trunk"));
  	x.add(new Message("A broken leg"));
  	x.add(new Message("Donald Trump"));
  	x.add(new Message("Homosexuality"));
  	x.add(new Message("Some pineapples"));
  	x.add(new Message("An automatic rifle"));
  	x.add(new Message("Trench warfare"));
  	x.add(new Message("Insurance"));
  	x.add(new Message("Entry speeches"));
  	x.add(new Message("Zyklon B"));
  	x.add(new Message("Buret funnels"));
  	x.add(new Message("Spectator ions"));
  	x.add(new Message("Monkeys with typewriters"));
  	x.add(new Message("Methacton's drumline"));
  	x.add(new Message("Springford's drumline"));
  	x.add(new Message("Ticking like a clock"));
  	x.add(new Message("A 1.5 liter hydrogen peroxide bomb"));
  	x.add(new Message("The Titanic"));
  	x.add(new Message("The moon"));
  	x.add(new Message("Jupiter"));
  	x.add(new Message("Shelton"));
  	x.add(new Message("Brendan"));
  	x.add(new Message("PJ"));
  	x.add(new Message("Vincent"));
  	x.add(new Message("Matthew"));
  	x.add(new Message("Fu"));
  	x.add(new Message("Hira"));
  	x.add(new Message("Joanna"));
  	x.add(new Message("Jeff"));
  	x.add(new Message("The Muslim League"));
  	x.add(new Message("George Washington"));
  	x.add(new Message("Mark Zuckerberg"));
  	x.add(new Message("School Chromebooks"));
  	x.add(new Message("Unidentified liquids"));
  	x.add(new Message("Half of a bagel"));
  	x.add(new Message("Sticky keys"));
  	x.add(new Message("A dress"));
  	x.add(new Message("Excalibur"));
  	x.add(new Message("Rebar"));
  	x.add(new Message("Rigorous fitness training"));
  	x.add(new Message("Obesity"));
  	x.add(new Message("Yale University"));
  	x.add(new Message("Socks and Sandals"));
  	x.add(new Message("The Roman Empire"));
  	x.add(new Message("Hitler's left testicle"));
  	x.add(new Message("Dank memes"));
  	x.add(new Message("Danker memes"));
  	x.add(new Message("Dankest memes"));
  	x.add(new Message("Heath Ledger's Joker"));
  	x.add(new Message("Eurasia"));
  	x.add(new Message("The Indian subcontinent"));
  	x.add(new Message("Antarctica"));
  	x.add(new Message("Misspelled words"));
  	x.add(new Message("1"));
  	x.add(new Message("2"));
  	x.add(new Message("3"));
  	x.add(new Message("4"));
  	x.add(new Message("5"));
  	x.add(new Message("6"));
  	x.add(new Message("7"));
  	x.add(new Message("8"));
  	x.add(new Message("9"));
  	x.add(new Message("10"));
  	x.add(new Message("69"));
  	x.add(new Message("420"));
  	x.add(new Message("Open-toed shoes"));
  	x.add(new Message("College textbooks"));
  	x.add(new Message("AP courses"));
  	x.add(new Message("That one itch you can't scratch"));
  	x.add(new Message("Dicks"));
  	x.add(new Message("Vaginas"));
  	x.add(new Message("Socialism"));
  	x.add(new Message("Capitalism"));
  	x.add(new Message("HIV"));
  	x.add(new Message("Smallpox"));
  	x.add(new Message("Poor people"));
  	x.add(new Message("Debt"));
  	x.add(new Message("The U.S."));
  	x.add(new Message("Grover Cleveland"));
  	x.add(new Message("Antisemitism"));
  	x.add(new Message("Homophobia"));
  	x.add(new Message("Lynching"));
  	x.add(new Message("This chatbot"));
  	x.add(new Message("Ur mom"));
  	x.add(new Message("Your mother"));
  	x.add(new Message("Snow White's 7 dwarves"));
  	x.add(new Message("Sauron"));
  	x.add(new Message("Darth Vader"));
  	x.add(new Message("Order 66"));
  	x.add(new Message("BDSM"));
  	x.add(new Message("Picnics"));
  	x.add(new Message("Finland"));
  	x.add(new Message("China"));
  	x.add(new Message("Russia"));
  	x.add(new Message("Mao Zedong"));
  	x.add(new Message("J.F.K."));
  	x.add(new Message("Lee Harvey Oswald"));
  	x.add(new Message("Trickle down economics"));
  	x.add(new Message("The void"));
  	x.add(new Message("Entropy"));
  	x.add(new Message("Nuclear weapons"));
  	x.add(new Message("3.5 billion penises"));
  	x.add(new Message("Parkinson's"));
  	x.add(new Message("Cystic Fibrosis"));
  	x.add(new Message("Manifest Destiny"));
  	x.add(new Message("Suicide"));
  	x.add(new Message("Happiness"));
  	x.add(new Message("Depression"));
  	x.add(new Message("Cthulu"));
  	x.add(new Message("Cosmic entities"));
  	x.add(new Message("The Red Scare"));
  	x.add(new Message("Jim Crow Laws"));
  	x.add(new Message("Teenage pregnancy"));
  	x.add(new Message("Henry VIII"));
  	x.add(new Message("Emperor Nero"));
  	x.add(new Message("Shaka Zulu"));
  	x.add(new Message("Christianity"));
  	x.add(new Message("Buddhist Terrorism"));
  	x.add(new Message("The Galactic Trade Federation"));
  	x.add(new Message("Emperor Palpatine"));
  	x.add(new Message("A duel to the death"));
  	x.add(new Message("Blood spilt"));
  	x.add(new Message("A red horizon"));
  	x.add(new Message("He Who Is Of Ten-thousand Faces"));
  	x.add(new Message("Seizures"));
  	x.add(new Message("Non-Euclidean Geometry"));
  	x.add(new Message("Procrastination"));
  	x.add(new Message("The military industrial complex"));
  	x.add(new Message("Hairy Dildos"));
  	x.add(new Message("Feasting Octopi"));
  	x.add(new Message("99 butts"));
  	x.add(new Message("A slimy boi"));
  	x.add(new Message("Down syndrome"));
  	x.add(new Message("A string of firecrackers"));
  	x.add(new Message("Eggs"));
  	x.add(new Message("Flouride"));
  	x.add(new Message("Gay frogs"));
  	x.add(new Message("Potato Chips"));
  	x.add(new Message("Semen"));
  	x.add(new Message("Black people"));
  	x.add(new Message("White people"));
  	x.add(new Message("The Holocaust"));
  	x.add(new Message("Anne Frank"));
  	x.add(new Message("Powdered Milk"));
  	x.add(new Message("Snowflakes"));
  	x.add(new Message("134 thirsty wildebeest"));
  	x.add(new Message("Serotonin"));
  	x.add(new Message("Profit"));
  	x.add(new Message("???"));
  	x.add(new Message("Antimatter"));
  	x.add(new Message("A nuclear reactor"));
  	x.add(new Message("Jetpacks"));
  	x.add(new Message("Flying Squirrels"));
  	x.add(new Message("Half of Pakistan"));
  	x.add(new Message("ISIS"));
  	x.add(new Message("Al Qaeda"));
  	x.add(new Message("9/11"));
  	x.add(new Message("Thunderstorms"));
  	x.add(new Message("Genghis Khan"));
  	x.add(new Message("3 fingers"));
  	x.add(new Message("Caffienated children"));
  	x.add(new Message("Dwarf tossing"));
  	x.add(new Message("Salad tossing"));
  	x.add(new Message("A sunny day"));
  	x.add(new Message("NullPointerException"));
  	x.add(new Message("Error ErrorID:13i4de23"));
  	x.add(new Message("17 anuses"));
  	x.add(new Message("Non-vaginal intercourse"));
  	x.add(new Message("An electric toothbrush"));
  	x.add(new Message("Scottish kilts"));
  	x.add(new Message("The Belgian Congo"));
  	x.add(new Message("Adolf Hitler's mariachi band"));
  	x.add(new Message("Eyeholes"));
  	x.add(new Message("8 shoelaces for 1 shoe"));
  	x.add(new Message("Nut Cheerios"));
  	x.add(new Message("The blood of the innocent"));
  	x.add(new Message("Video games"));
  	x.add(new Message("Spite"));
  	x.add(new Message("Sprite"));
  	x.add(new Message("Dr. Seuss"));
  	x.add(new Message("Baby boomers"));
  	x.add(new Message("Saudia Arabia"));
  	x.add(new Message("Black Lives Matter"));
  	x.add(new Message("Void Juice"));
  	x.add(new Message("Shelton"));
  	x.add(new Message("God"));
  	x.add(new Message("Joanna"));
  	x.add(new Message("Brendan"));
  	x.add(new Message("PJ"));
  	x.add(new Message("Jeff"));
  	x.add(new Message("Nick"));
  	x.add(new Message("Nick"));
  	x.add(new Message("Matthew"));
  	x.add(new Message("Fu"));
  	x.add(new Message("Vincent"));
  	x.add(new Message("AP Tests"));
  	x.add(new Message("Rock Candy"));
  	x.add(new Message("Karl Marx"));
  	x.add(new Message("Dante's Divine Comedy"));
  	x.add(new Message("The Syrian Civil War"));
  	x.add(new Message("AIDS but contagious"));
  	x.add(new Message("Intravenous drug use"));
  	x.add(new Message("Infected wounds"));
  	x.add(new Message("Pre-Geneva Convention weapons"));
  	x.add(new Message("Biological warfare"));
  	x.add(new Message("Wario's Wares"));
  	x.add(new Message("Waluigi"));
  	x.add(new Message("Sunflower seeds"));
  	x.add(new Message("High blood pressure"));
  	x.add(new Message("Security cameras"));
  	x.add(new Message("Bad coding practices"));
  	x.add(new Message("Gunshots"));
  	x.add(new Message("Forced Windows update"));
  	x.add(new Message("Really big arrays"));
  	x.add(new Message("Unlimited pizza"));
  	x.add(new Message(""));
	}
	
	
}
