name: Docker Image Release CI

# on:
#   release:
#     types: ["published"]

# only pushes when there is a tag in commit
on:
  push:
    tags: 
      - 'v*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/valorant-bot:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/valorant-bot:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/valorant-bot:buildcache,mode=max
