// -*-coding:utf-8 -*-
// -------------------------------------------------------------------------
// Path          - DiscordBot/Structures/Validation/eventNames.js
// Git           - https://github.com/The-Repo-Club
// Author        - The-Repo-Club [wayne6324@gmail.com]
// Start On      - Wed 23 February 2022, 12:04:54 pm (GMT)
// Modified On   - Wed 23 February 2022, 12:09:12 pm (GMT)
// -------------------------------------------------------------------------

module.exports = {
	Events: [
		"applicationCommandCreate",
		"applicationCommandDelete",
		"applicationCommandUpdate",
		"channelCreate",
		"channelDelete",
		"channelPinsUpdate",
		"channelUpdate",
		"debug",
		"emojiCreate",
		"emojiDelete",
		"emojiUpdate",
		"error",
		"guildBanAdd",
		"guildBanRemove",
		"guildCreate",
		"guildDelete",
		"guildIntegrationsUpdate",
		"guildMemberAdd",
		"guildMemberAvailable",
		"guildMemberRemove",
		"guildMembersChunk",
		"guildMemberUpdate",
		"guildUnavailable",
		"guildUpdate",
		"interaction",
		"interactionCreate",
		"invalidated",
		"invalidRequestWarning",
		"inviteCreate",
		"inviteDelete",
		"message",
		"messageCreate",
		"messageDelete",
		"messageDeleteBulk",
		"messageReactionAdd",
		"messageReactionRemove",
		"messageReactionRemoveAll",
		"messageReactionRemoveEmoji",
		"messageUpdate",
    "modalSubmit",
		"presenceUpdate",
		"rateLimit",
		"ready",
		"roleCreate",
		"roleDelete",
		"roleUpdate",
		"shardDisconnect",
		"shardError",
		"shardReady",
		"shardReconnecting",
		"shardResume",
		"stageInstanceCreate",
		"stageInstanceDelete",
		"stageInstanceUpdate",
		"stickerCreate",
		"stickerDelete",
		"stickerUpdate",
		"threadCreate",
		"threadDelete",
		"threadListSync",
		"threadMembersUpdate",
		"threadMemberUpdate",
		"threadUpdate",
		"typingStart",
		"userUpdate",
		"voiceStateUpdate",
		"warn",
		"webhookUpdate",
	],
};
